# Generated by Django 2.0.7 on 2018-11-04 09:51

import DownloadAbleFiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('file', models.ImageField(null=True, upload_to=DownloadAbleFiles.models.upload_image_path)),
                ('python_check_box', models.BooleanField(default=False)),
                ('java_check_box', models.BooleanField(default=False)),
            ],
        ),
    ]
