# Generated by Django 2.0.7 on 2018-11-04 10:08

import DownloadAbleFiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DownloadAbleFiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=DownloadAbleFiles.models.upload_image_path),
        ),
    ]
