# Generated by Django 2.0.7 on 2018-12-15 20:33

import DownloadAbleFiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DownloadAbleFiles', '0002_auto_20181104_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='file',
            field=models.FileField(upload_to=DownloadAbleFiles.models.upload_image_path),
        ),
    ]
